In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
a = np.array([[10, 2.7, 3.6, 5], [-100, 5, -2, 10], [120, 20, 40, 50]],
             dtype=np.float64)
print(a)

[[  10.     2.7    3.6    5. ]
 [-100.     5.    -2.    10. ]
 [ 120.    20.    40.    50. ]]


In [ ]:
def normalize(x, axis, method, minmax_range=(0, 1)):
    if method == 'z-score':
        scale_a = preprocessing.scale(x, axis=axis)
    elif method == 'minmax':
        scale_a = preprocessing.minmax_scale(
            x, axis=axis,
            feature_range=minmax_range)  # default feature range 0~1
    return scale_a

# Z-Score

In [ ]:
# 改變axis，看看結果如何變化
axis = 0
scale_a = normalize(a, axis, method='z-score')
print(scale_a)

[[ 0.         -0.85170713 -0.55138018 -0.82760589]
 [-1.22474487 -0.55187146 -0.852133   -0.57932412]
 [ 1.22474487  1.40357859  1.40351318  1.40693001]]


In [ ]:
print(scale_a.std(axis=axis))
print(scale_a.mean(axis=axis))

[1. 1. 1. 1.]
[ 0.00000000e+00  1.48029737e-16  0.00000000e+00 -7.40148683e-17]


# Maxmin Scale

In [ ]:
# 改變axis，看看結果如何變化
axis = 0
# 改變minmax_range看看結果如何變化
scale_a = normalize(a, axis, method='minmax', minmax_range=(0, 1))
print(scale_a)

[[0.5        0.         0.13333333 0.        ]
 [0.         0.13294798 0.         0.11111111]
 [1.         1.         1.         1.        ]]


In [ ]:
print(scale_a.max(axis=axis))
print(scale_a.min(axis=axis))

[1. 1. 1. 1.]
[0. 0. 0. 0.]
